"""add_api_key_rate_limits_table

Revision ID: d8013109febc
Revises: 241cc117ff16
Create Date: 2026-01-21 06:23:48.582577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8013109febc'
down_revision: Union[str, Sequence[str], None] = '241cc117ff16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_rate_limits',
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('api_key_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key_rate_limits')
    # ### end Alembic commands ###
